# Generated by Django 4.2.4 on 2023-10-17 06:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realName', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('class_name', models.CharField(max_length=255)),
                ('studentId', models.CharField(max_length=255)),
                ('imagePath', models.ImageField(upload_to='couriers/')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickupAddress', models.CharField(max_length=255)),
                ('deliveryAddress', models.CharField(max_length=255)),
                ('pickupInfo', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=255)),
                ('expressSize', models.CharField(max_length=255)),
                ('expressWeight', models.CharField(max_length=255)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='手机号长度必须为11位', regex='^.{11}$')], verbose_name='手机号')),
                ('username', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(code='nomatch', message='用户名必须为1-8位汉字', regex='^[一-龥]{1,8}$')], verbose_name='用户名')),
                ('avatar', models.ImageField(upload_to='avatars/', verbose_name='用户头像')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='customuser_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
